// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ledger/archive/query.proto

package archive // import "github.com/hyperledger/fabric/protos/ledger/archive"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// BlockfileVerifyResponse -- Verify Result
type BlockfileVerifyResponse struct {
	Pass                 bool     `protobuf:"varint,1,opt,name=pass,proto3" json:"pass"`
	ChannelID            string   `protobuf:"bytes,2,opt,name=channelID,proto3" json:"channelID"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockfileVerifyResponse) Reset()         { *m = BlockfileVerifyResponse{} }
func (m *BlockfileVerifyResponse) String() string { return proto.CompactTextString(m) }
func (*BlockfileVerifyResponse) ProtoMessage()    {}
func (*BlockfileVerifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_2668f438253f9c6d, []int{0}
}
func (m *BlockfileVerifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockfileVerifyResponse.Unmarshal(m, b)
}
func (m *BlockfileVerifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockfileVerifyResponse.Marshal(b, m, deterministic)
}
func (dst *BlockfileVerifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockfileVerifyResponse.Merge(dst, src)
}
func (m *BlockfileVerifyResponse) XXX_Size() int {
	return xxx_messageInfo_BlockfileVerifyResponse.Size(m)
}
func (m *BlockfileVerifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockfileVerifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlockfileVerifyResponse proto.InternalMessageInfo

func (m *BlockfileVerifyResponse) GetPass() bool {
	if m != nil {
		return m.Pass
	}
	return false
}

func (m *BlockfileVerifyResponse) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func init() {
	proto.RegisterType((*BlockfileVerifyResponse)(nil), "archive.BlockfileVerifyResponse")
}

func init() { proto.RegisterFile("ledger/archive/query.proto", fileDescriptor_query_2668f438253f9c6d) }

var fileDescriptor_query_2668f438253f9c6d = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xb1, 0x0a, 0xc2, 0x30,
	0x14, 0x45, 0xa9, 0x88, 0xda, 0x8c, 0x59, 0x2c, 0xe2, 0x50, 0x9c, 0x3a, 0x48, 0x32, 0xf4, 0x0f,
	0x8a, 0x8b, 0xb8, 0x75, 0x70, 0x70, 0x4b, 0xe3, 0x6b, 0x13, 0x8c, 0x4d, 0x7c, 0x69, 0x85, 0xfe,
	0xbd, 0xd0, 0x04, 0xd4, 0xed, 0x72, 0xe0, 0x70, 0xb8, 0x64, 0x67, 0xe0, 0xde, 0x01, 0x72, 0x81,
	0x52, 0xe9, 0x37, 0xf0, 0xd7, 0x08, 0x38, 0x31, 0x87, 0x76, 0xb0, 0x74, 0x1d, 0xe1, 0xe1, 0x42,
	0xb6, 0x95, 0xb1, 0xf2, 0xd1, 0x6a, 0x03, 0x57, 0x40, 0xdd, 0x4e, 0x35, 0x78, 0x67, 0x7b, 0x0f,
	0x94, 0x92, 0xa5, 0x13, 0xde, 0x67, 0x49, 0x9e, 0x14, 0x9b, 0x7a, 0xde, 0x74, 0x4f, 0x52, 0xa9,
	0x44, 0xdf, 0x83, 0x39, 0x9f, 0xb2, 0x45, 0x9e, 0x14, 0x69, 0xfd, 0x05, 0x95, 0x24, 0x47, 0x8b,
	0x1d, 0x53, 0x93, 0x03, 0x0c, 0x71, 0xd6, 0x8a, 0x06, 0xb5, 0x0c, 0x55, 0xcf, 0x22, 0x8c, 0xf1,
	0x5b, 0xd9, 0xe9, 0x41, 0x8d, 0x0d, 0x93, 0xf6, 0xc9, 0x7f, 0x24, 0x1e, 0x24, 0x1e, 0x24, 0xfe,
	0x7f, 0xa3, 0x59, 0xcd, 0xb8, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0x33, 0x15, 0xf7, 0xa3, 0xdf,
	0x00, 0x00, 0x00,
}
